name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    # Установка требований
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Форматирование и linting
    - name: Format code with Black & isort
      run: |
        black .
        isort .
    
    - name: Run linters
      run: |
        flake8 .
        pylint src/
        mypy src/
    
    # Запуск автотестов
    - name: Run tests
      run: |
        coverage run -m pytest
        coverage report
    
    # Анализ безопасности
    - name: Check security vulnerabilities
      run: safety check
      
    # Дополнительные анализы
    - name: DeepSource analysis
      if: github.event_name != 'pull_request'
      run: deepsource analyze
